### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by rishi-raj-jain** [brandonroberts/astro-analog-bling#1]
<img width="1136" alt="Screenshot 2023-03-01 at 9 30 36 PM" src="https://user-images.githubusercontent.com/46300090/222194044-9b52be3e-2d14-4e3f-87a2-9b18eba1b96d.png">

**Comment by brandonroberts** [comment]
Will you share some environment info? `npm run build` works for me on node 18.13.0

**Comment by rishi-raj-jain** [comment]
Node v16
Npm v8
Macbook M1 Pro

**Comment by brandonroberts** [comment]
Try with node `v16.17.0`
